server:
  port: 9901
  servlet:
    context-path: /adapter-server

serverAddress: 106.14.244.179

spring:
  application:
    name: adapter-server
  rabbitmq:
    addresses: ${serverAddress}:4369,${serverAddress}:5671,${serverAddress}:5672
    connection-timeout: 15000
    listener:
      # 最好不要在代码里写死配置信息，尽量使用这种方式也就是配置文件的方式
      # 在代码里使用 	${}	方式进行设置配置: ${spring.rabbitmq.listener.order.exchange.name}
      order:
        exchange:
          durable: true
          key: order.*
          name: order-exchange
          type: topic
      # 表示消费者消费成功消息以后需要手工的进行签收(ack)，默认为auto
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
    password: guest
    username: guest
    virtual-host: /

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka-server/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}