server:
  port: 9910
  servlet:
    context-path: /core-server

spring:
  application:
    name: core-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka-server/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${server.port}